version: '3.8'

services:
  backend:
    build: ./backend  # Path to Spring Boot project
    ports:
      - "8080:8080"
    networks:
      - app-network

  #frontend:
  #  build: ./frontend  # Path to Vue project
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - backend
  #  networks:
  #    - app-network

networks:
  app-network:
    driver: bridge