/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./components/AccountForm.vue')['default']
    AccountSelector: typeof import('./components/AccountSelector.vue')['default']
    AccountsList: typeof import('./pages/accounts/components/AccountsList.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    BillsOverview: typeof import('./pages/dashboard/overview/components/BillsOverview.vue')['default']
    BudgetDialog: typeof import('./pages/budgets/components/BudgetDialog.vue')['default']
    CarsInfo: typeof import('./pages/dashboard/overview/components/CarsInfo.vue')['default']
    ConfirmDialog: typeof import('./components/shared/ConfirmDialog.vue')['default']
    FeatureCard: typeof import('./pages/home/components/Features/FeatureCard.vue')['default']
    Features: typeof import('./pages/home/components/Features/index.vue')['default']
    ForgotPassword: typeof import('./components/auth/ForgotPassword.vue')['default']
    Hero: typeof import('./pages/home/components/hero/Hero.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    LocaleToggler: typeof import('./components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./components/blocks/Logo.vue')['default']
    PaymentDialog: typeof import('./pages/payments/components/PaymentDialog.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    RentalByType: typeof import('./pages/dashboard/overview/components/RentalByType.vue')['default']
    RentalFrequency: typeof import('./pages/dashboard/overview/components/RentalFrequency.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/blocks/Settings.vue')['default']
    StatCardOverview: typeof import('./pages/dashboard/overview/components/StatCardOverview.vue')['default']
    ThemeToggler: typeof import('./components/blocks/ThemeToggler.vue')['default']
    ToggleDirection: typeof import('./components/blocks/ToggleDirection.vue')['default']
    TransactionDialog: typeof import('./pages/transactions/components/TransactionDialog.vue')['default']
    UpcomingPayments: typeof import('./pages/expenses/components/UpcomingPayments.vue')['default']
  }
}
